### PR TITLE
Add missing argoverse entries and sort by # of citations

### PR DESCRIPTION
**Pull request by johnwlambert**
Hi @daniel-bogdoll, thanks for compiling this list. I'm a co-author of the Argoverse datasets, and I added missing details about our datasets

I also figured the most appropriate way to sort the datasets would be by the influence/impact, as measured by # of citations to the corresponding dataset paper. As of Google Scholar today, the number of citations I found for many of these were:

KITTI 4566
nuScenes 837
Oxford Robot Car 765
Waymo Open Dataset 317
Argoverse 302
Semantic KITTI 295
Apolloscape 275
BDD 240
WildDash 59
Lyft L5 42
Cityscapes3D 5

### CODE REVIEW

**Comment by daniel-bogdoll** [comment]
Hey @johnwlambert , thanks for the PR! I'll merge it today or early next week. I like the idea of the influence, but this is hard to maintain I believe. Are you aware of any method that would pull such numbers with a script? This could enable us to automate this process every x weeks

**Comment by johnwlambert** [comment]
No problem. Unfortunately I don't know of any simple way to pull those numbers automatically. I think the citation ranking is pretty stable, though, currently.

**Comment by johnwlambert** [comment]
A gentle reminder about this update : - )

**Comment by daniel-bogdoll** [comment]
Hey John :) I quickly looked into it - the website is build from this file: https://github.com/daniel-bogdoll/ad-datasets/blob/main/my-app/src/data.js

The csv was created for a publication regarding the project. I will move these files into a "publication" folder to avoid further confusion. 

But obviously I'd like to see your input on the website, thus I will copy your entries manually so you don't have any additonal work :) Final question before I do so: Did you edit any of the orhter entries you have moved or only the Argoverse one?

**Comment by johnwlambert** [comment]
Ah I see, didn't realize that the csv wasn't being used.

All other entries should be identical -- I only edited the Argoverse entries.

**Pull request merged**
